python mrr.py --result_dir "./results_ensemble2_seed1/java" --pic_name "seed1_en2"
python mrr.py --result_dir "./results_ensemble2_seed3/java" --pic_name "seed3_en2"
python mrr.py --result_dir "./results_ensemble2_seed5/java" --pic_name "seed5_en2"
python mrr.py --result_dir "./results_ensemble2_seed7/java" --pic_name "seed7_en2"
python mrr.py --result_dir "./results_ensemble2_seed11/java" --pic_name "seed11_en2"
