python mrr.py --result_dir "./results_seed1_origin-full/java" --pic_name "seed1_switch2if"
python mrr.py --result_dir "./results_seed3_origin-full/java" --pic_name "seed3_switch2if"
python mrr.py --result_dir "./results_seed5_origin-full/java" --pic_name "seed5_switch2if"
python mrr.py --result_dir "./results_seed7_origin-full/java" --pic_name "seed7_switch2if"
python mrr.py --result_dir "./results_seed11_origin-full/java" --pic_name "seed11_switch2if"
