python mrr.py --result_dir "./results_ensemble3_code_new_notfix_seed1/java" --pic_name "seed1_switch2if"
python mrr.py --result_dir "./results_ensemble3_code_new_notfix_seed3/java" --pic_name "seed1_switch2if"
python mrr.py --result_dir "./results_ensemble3_code_new_notfix_seed5/java" --pic_name "seed1_switch2if"
# python mrr.py --result_dir "./results_ensemble3_code_new_seed3/java" --pic_name "seed1_switch2if"
# python mrr.py --result_dir "./results_ensemble3_code_new_seed5/java" --pic_name "seed1_switch2if"
# python mrr.py --result_dir "./results_ensemble3_code_new_seed7/java" --pic_name "seed1_switch2if"
# python mrr.py --result_dir "./results_ensemble3_code_new_seed11/java" --pic_name "seed1_switch2if"
# python mrr.py --result_dir "./results_query_ensemble4_train_seed3/java" --pic_name "seed3_switch2if"
# python mrr.py --result_dir "./results_query_ensemble4_train_seed5/java" --pic_name "seed5_switch2if"
# python mrr.py --result_dir "./results_query_ensemble4_train_seed7/java" --pic_name "seed7_switch2if"
# python mrr.py --result_dir "./results_query_ensemble4_train_seed11/java" --pic_name "seed11_switch2if"
